### ISSUE TITLE
Add parallel implementation capability to buildBench?

### ISSUE THREAD

**Issue by kdkorthauer** [areyesq89/SummarizedBenchmark#10]
I was thinking it might be useful to add parallel evaluation capability to the `buildBench` method. For large datasets (e.g. GWAS with millions of tests) or a large number of methods (e.g. IHW with many alphas) running the methods can take a while. This might be as simple as replacing some the lapply calls with mclapply, or we could use other parallel interfaces.

**Comment by pkimes** [comment]
I think this makes a lot of sense. I can look into adding BiocParallel support.

**Comment by pkimes** [comment]
Feature for running each method in parallel with `BiocParallel` added in commit 8f812c3db9b0 .
@kdkorthauer feel free to re-open if you have any issues or had anything else in mind.

One problem I haven't really thought about is how to run methods which require parallelizing in parallel (i.e. 2 layers of parallelization). e.g. if we wanted to benchmark `DESeq2` with multiple designs and we want to run each with the `DESeq` `parallel = TRUE` parameter.
