### ISSUE TITLE
Add `bpre =` parameter to `buildBench`

### ISSUE THREAD

**Issue by pkimes** [areyesq89/SummarizedBenchmark#14]
Was asked about the possibility of added a `bpre =` parameter option to `buildBench(..)` (similar to `bpost = ` but for pre-processing certain data columns for a specific method). 

This might help avoid the need of custom wrapper functions for the `bfunc =` parameter. (e.g. in `benchmark-fdr`, we currently have wrappers for FDRreg and lfdr).

**Comment by pkimes** [comment]
So I looked into this a little bit w.r.t. the wrapper functions being used in our [`common-BenchDesign.R` code](https://github.com/pkimes/benchmark-fdr/blob/a9929000cb8d732f28aea692b1b12417feb4dfce/datasets/R/common-BenchDesign.R) (which I think was the impetus for @kdkorthauer suggesting the `bpre =` parameter).

I tried to see if we could get rid of the two wrapper functions, [1] `clfdr_hickswrapper` and [2] `scott_fdrreg_hickswrapper` with or without a new `bpre =` parameter. The calls to add `scott_fdrreg_hickswrapper` to the `BenchDesign` can be rewritten without a `bpre =` parameter, but the call to add `clfdr_hickswrapper` can't be rewritten with or without a `bpre =` parameter. 

I think @kdkorthauer wanted the `bpre =` parameter primarily so the "main function" could be passed to `bfunc =` unaltered, and the correct package name and version could be returned during the `buildBench` process (correct me if I'm wrong). Unfortunately, it looks like this isn't possible for some cases (e.g. `clfdr_hickswrapper`) because the wrapper actually includes a fair bit of work. One (clunky?) workaround would be to add a new `bmeta =` parameter that would take a function as input, solely for the purpose of extracting package name/version meta information. For the `clfdr_hickswrapper` function, the call would look something like:
```
bd %<>% addBMethod(bname = "lfdr",
                   bfunc = clfdr_hickswrapper,
                   bmeta = fdrtool::fdrtool,
                   unadj_p = pval, groups = IHW::groups_by_filter(ind_covariate, 20))
```

Thoughts?
As a start, I'll modify `common-BenchDesign.R` to get rid of the `scott_fdrreg_hickswrapper` wrapper function (although we'll lose some of the checks written into the wrapper function, I think it'll be fine).

**Comment by kdkorthauer** [comment]
Correct, I was thinking of adding something like a `bpre` parameter primarily so the "main function" could be passed in and the package name and version stored properly. As a last resort, I think using the `bmeta` option could work. But it's not ideal that it's divorced from the wrapper completely. Great that we could already eliminate one of the wrappers!

**Comment by areyesq89** [comment]
I like having the `bmeta` option for those difficult cases. It could even take directly package names and hard-coded values, the latter thinking about R wrappers involving software that is not in R invoked using `system` calls.

**Comment by kdkorthauer** [comment]
Looking at `clfdr_hickswrapper` again, I see why it's not possible (or even ideal) to handle it with something like `bpre` - it actually isn't a method that has it's own package (that we are aware of). Since it uses `fdrtool` but applies it in a novel way (over groups), but `IHWPaper` implemented it, it's not even clear which package/version to cite. Maybe both?

**Comment by pkimes** [comment]
Thanks for the feedback! Thinking about this more, I'm planning on moving forward with adding the `bmeta=` as an "advanced" parameter option. 

The parameter will modify the info in the corresponding row of the `colData` of the created `SummarizedBenchmark` object. 

For example, if the default `colData` for a `buildBench` call looked like this:
```
$ b <- BenchDesign(tdat)
$ b %<>% addBMethod(blabel = "bonf", bfunc = p.adjust,
$                   p = pval, method = "bonferroni")
$ b %<>% addBMethod(blabel = "BH", bfunc = p.adjust,
$                   p = pval, method = "BH")
$ buildBench(b) %>% colData
 DataFrame with 2 rows and 8 columns
         bfunc    bpost  param.p param.method   is_anon pkg_name pkg_vers
      <factor> <factor> <factor>     <factor> <logical> <factor> <factor>
 bonf p.adjust       NA     pval "bonferroni"     FALSE    stats    3.4.2
 BH   p.adjust       NA     pval         "BH"     FALSE    stats    3.4.2
           blabel
      <character>
 bonf        bonf
 BH            BH
```
The `bmeta=` parameter can be added to manually specify columns in `colData`.
```
$ b %<>% addBMethod(blabel = "bonf", bfunc = p.adjust,
$                   p = pval, method = "bonferroni", 
$                   bmeta = list(pkg_vers = "100", pkg_name = "notarealpkg"))
$ buildBench(b) %>% colData
 DataFrame with 2 rows and 8 columns
         bfunc    bpost  param.p param.method   is_anon    pkg_name pkg_vers
      <factor> <factor> <factor>     <factor> <logical>    <factor> <factor>
 bonf p.adjust       NA     pval "bonferroni"     FALSE notarealpkg      100
 BH   p.adjust       NA     pval         "BH"     FALSE       stats    3.4.2
           blabel
      <character>
 bonf        bonf
 BH            BH
```

I'm currently planning on writing the `bmeta =` parameter to accept a named list with the following behavior: 
* list entry `pkg_func`should be a function, and will determine `pkg_name` and `pkg_vers`.
* list entries `pkg_name`, `pkg_vers` will overwrite entries in `colData` (but `pkg_func` takes priority).
* other named list entries will be added as new columns with prefix `meta_`.

I'm planning on also adding new columns for `vers_src` to `colData` which takes values in: `bfunc`, `none`, `bmeta_func`, `bmeta_manual` to keep track of how the package name and version were determined.
 
Also, I'll switch these columns from `<factor>`s to `<character>`s, unless people think `<factor>` makes more sense.

**Comment by pkimes** [comment]
This feature is now implemented in Pull Request #16.

**Comment by kdkorthauer** [comment]
Awesome! When you say 
> but `pkg_func` takes priority

That is referring to the *user* - that the user should first rely on `pkg_func` and only specify the other `bmeta` arguments in unusual cases, correct? Since `pkg_name`,`pkg_vers` will overwrite it seems like they actually "take priority".

**Comment by pkimes** [comment]
Actually, not quite! 

So the main function is specified as `bfunc`.
`pkg_func` is an argument that can be specified to `bmeta` which will be parsed to determine the package name and version. This will (or at least *should*) overwrite `pkg_name`, `pkg_vers` manually specified to `bmeta`.

As an example, for our `benchmark-fdr` project, we could modify the `lfdr` method to:
```
 bd %<>% addBMethod("lfdr",
                     clfdr_hickswrapper,
                     bmeta = list(pkg_func = fdrtool),
                     unadj_p = pval, groups = IHW::groups_by_filter(ind_covariate, 20))
```

**Comment by kdkorthauer** [comment]
Got it; that makes sense!

**Comment by pkimes** [comment]
Closing this for now since we've implemented the (somewhat clunky) `bmeta =` parameter option for specifying the correct "version" for a method. (This is also now documented in the vignette [here](https://github.com/areyesq89/SummarizedBenchmark/blob/09c63c573307269d4aad8e6a0534f0495c3a1050/vignettes/CompleteWorkflow.Rmd#manually-modifying-version-metadata)).
