### ISSUE TITLE
Is this appropriate for working with multiple datasets and multiple steps of analysis?

### ISSUE THREAD

**Issue by Shians** [areyesq89/SummarizedBenchmark#25]
I am developing a benchmarking package and am considering whether or not I should use this package as a basis. The alternative I'm considering is just constructing a simple tibble with format like so

```
# A tibble: 6 x 3
  data       method    result         
  <chr>      <chr>     <list>         
1 sc_10x     unimputed <dbl [10 × 20]>
2 sc_10x     drimpute  <dbl [10 × 20]>
3 sc_celseq  unimputed <dbl [10 × 20]>
4 sc_celseq  drimpute  <dbl [10 × 20]>
5 sc_dropseq unimputed <dbl [10 × 20]>
6 sc_dropseq drimpute  <dbl [10 × 20]>
```

So the main reservations I have about using SummarizedBenchmarks is that

1. It appears to be fundamentally concerned with a single dataset. For me the input will be a list of datasets, SingleCellExperiments to be exact. So to work effectively with this structure I'd have to be constructing a list of SummarizeExperiments? It's then non-trivial to combine these together for a meaningful comparison between the data sets.
2. I can't see any facilities in the vignettes to support combinatoric multi-step designs, for example if I wanted to test combinations of normalisation methods and DE summary I'd have to write individual wrappers for each pairwise combination, supply them as methods. This is tedious by hand and suffers from repeated work, as for 1 normalisation method and 3 DE procedures I'd actually be doing the normalisation 3 times due to the wrappers. This wastage grows exponentially as the number of steps in the analysis grows.
3. Composability of the SummarizedBenchmark object. I haven't tried this out, but is there any intention to feed a SummarizedBenchmark object as data into another benchmark? For example I might want to benchmark the normalisation, then use the results of the normalisation to feed into the DE analysis. Is there any kind of facility in this package to chain things up cleanly in this way? From the tibble you can imagine I could calculate another column called `metric` and then feed the first 3 columns into a downstream analysis where result is transmuted further by some downstream method.

So given that I would like to set up benchmarks for multiple datasets in a combinatorial multi-step analysis, would you recommend using this package? I think DSC's model most closely matches what I'm hoping to do, but their Python interface + custom language is a very high cost dependency and their R interface is undocumented.

**Comment by pkimes** [comment]
Thanks for taking a look at SummarizedBenchmark!
Let me try to work through your questions.

1. [Q1 - Part I] You're correct - the package is designed with the idea of running methods on a single "data set". A data set can be any list, a list with a single SingleCellExperiment object, a data.frame, a tibble, ... If you have a list of SingleCellExperiments, it would just be quicker to run the same`BenchDesign` on each SingleCellExperiment separately. 

1. [Q1 - Part II] I'm not exactly sure what you mean by "meaningful comparisons between the data sets." Do you mind clarifying? Do you mean comparing the results of each method (i.e. the `result` column in your tibble) or performance metrics computed for each data set? I agree that trying to combine SummarizedExperiment objects would be hard, but I'm not sure when you'd *have* to do this with SummarizedBenchmark.

2. [Q2] You're correct - unfortunately, the package doesn't support multi-step designs as part of a single `buildBench()` process. Each method in a `BenchDesign` object is viewed as a separate process that will be executed independently. The approach that I might consider would be to have each step of the design be a separate `BenchDesign` object (as you suggested below). Obviously, the alternative if you're working with multi-step processes is to use a pipelining language or package, e.g. the [drake package](https://github.com/ropensci/drake). 

3. [Q3] Chaining SB processes should very much be possible. With the newest version of the package, in addition to the results, the returned SB object now also stores [1] the MD5 hash of the input data and [2] an option to check if the input `BenchDesign` has been updated, e.g. if the R package versions or parameters have changed. These can used as triggers to update downstream steps based on changes upstream in the workflow. That being said, unfortunately, there's no formal approach to building a workflow like this in the package. (I'm also not exactly sure how this could be best implemented - e.g. a new `BenchWorkflow` class container for `BenchDesigns` and a workflow definition slot? or ...) If there's genuine interest, I'd be happy think about this more (and would appreciate any/all help). 

I don't know what kind of package you're trying to develop, so it's hard for me to say yes/no to whether you should be considering SummarizedBenchmark as a base. If you try chaining (question 3 above) with the newest version of the package and it causes you too many headaches that I can't fix or you don't like the API at all, I won't blame you for trying something else.

I think DSC's definitely another great option.

**Comment by pkimes** [comment]
Let me know if you have any other questions!

**Comment by Shians** [comment]
Thanks for the very quick reply, I wanted to further flesh out my package before responding to give a better idea of what I'd like to do. I think there's enough in there now to give a sense of what I aim to do.

https://github.com/shians/cellbench

The Introduction vignette gives a brief overview of what the package is about. Fundamentally there's one data object, the `benchmark_tbl` and one function `apply_methods`. I see the calculation of metrics as conceptually identical to applying a method so it simplifies the interface.

I think what I'm trying to do is a much more dumbed down version of what SummarizedBenchmark offers. The primary goal is to make it easy to set up and evaluate combinatoric methods benchmarks and keep all the data structures very simple so they can be manipulated in common ways. Ideally at any point an user can "opt-out" of the framework and play around with simple data.frames or lists to finish their benchmarking.

For the moment I'm going to work on CellBench with the tibble structure, but I think I'm leaving myself the option to swap around internals for SummarizedBenchmark in the future.

**Comment by pkimes** [comment]
Hi @Shians 

Thanks for the follow up! Sounds like a great project. Look forward to seeing what you build! Feel free to re-open this issue or open a new one if you have any more issues/questions.
