### ISSUE TITLE
Should estimatePerformanceMetrics be calculatePerformanceMetrics?

### ISSUE THREAD

**Issue by Shians** [areyesq89/SummarizedBenchmark#26]
Sorry for this nitpicking, but as far as I'm aware the performance metric is calculated exactly based on the output of the method and no estimation is involved. So it would make more sense to name it `calculatePerformanceMetric` or `computePerformanceMetric`? I believe you can just rename the function and write `estimatePerformanceMetric <- calculatePerformanceMetric` somewhere to maintain compatibility for existing users.

**Comment by pkimes** [comment]
Going to defer this question to @areyesq89, but I think it depends on whether the "metric" is an estimand (we estimate the estimand) or an estimator (we compute the estimator). Either seems reasonable to me. (When we wrote this, we viewed the "performance metric" to refer to the estimand.)

**Comment by areyesq89** [comment]
I agree with @pkimes. I'm leaving it 'as is' and closing the issue for the moment, but I'm open to further discussion if needed.
