### ISSUE TITLE
Allow more flexibility with "addDefaultMetrics"?

### ISSUE THREAD

**Issue by pkimes** [areyesq89/SummarizedBenchmark#7]
In addition to default metrics being added based on assay name, it would be nice to have optional parameters `assay =NULL` and `metric =NULL` to add metrics to non-standard assay names. 

For example, if a user creates an assay named `myassay` and they want to add "TPR", "FPR", then:
```
sb %<>% addDefaultMetrics(assay = "myassay", metric = c("TPR", "FPR"))
```

Obviously would be nice if this also included checks for "assay - metric" compatibility.

**Comment by areyesq89** [comment]
Great suggestion! This enhancement has been implemented in https://github.com/areyesq89/SummarizedBenchmark/commit/2ffd1667ca9b24f00c7d18b0f4c18c256fd3dbc8
