### ISSUE TITLE
How to use assayNames when there is no ground truth?

### ISSUE THREAD

**Issue by kdkorthauer** [areyesq89/SummarizedBenchmark#9]
I’m having trouble using the `assayNames` method on data with no ground truth.  Without using the assayNames method, the following is successful:

``` 
names(assays(sb)) <- names(rowData(sb)) <- names(sb@performanceMetrics) <- "qvalue"
sb <- addDefaultMetrics(sb)
```

If instead I try 

```
assayNames(sb) <- "qvalue"
sb <- addDefaultMetrics(sb)
```

I get the error “Error in validityMethod(object) : Not all assays have a corresponding ground truth column in rowData”.  But `elementMetadata( rowData( sb ) )$colType` returns "groundTruth". What am I missing? In this case should I manually set the names as in the first code chunk above?

**Comment by areyesq89** [comment]
Thanks for the detailed report! Could you try to install the latest version of the master branch?

I've added a bit of flexibility to the class. Previously, ground truth columns needed to be present in the `rowData` even if the values of these columns were all NAs. I added a bit more flexibility to this (I guess users won't always have ground truths). Now you should be able to do something like the code below without error messages:

```
data(sb)
rowData( sb ) <- NULL
assayNames(sb)[2] <- "log2FC"
validObject(sb)
```

**Comment by kdkorthauer** [comment]
Success! Thanks!

**Comment by kdkorthauer** [comment]
Using `assayNames` method to rename the default assay (`bench`) when there is no ground truth *and* there are multiple `rowData` columns (e.g. an `ind_covariate` column) throws this error:
```
Error in if (any(truthCol)) { : missing value where TRUE/FALSE needed
```
Works fine if the independent covariate column of `rowData` is removed. Is there a way to increase the flexibility of `assayNames` further? Or should we store the independent covariate elsewhere?

**Comment by kdkorthauer** [comment]
Tried again, and now the `assayNames` method doesn't throw an error, but there are downstream problems with `estimatePerformanceMetrics`. Here is a reproducible example with a subset of the SB object I'm working with:

```
library(SummarizedBenchmark)
library(R.utils)
library(ggplot2)
sourceDirectory("/n/irizarryfs01_backed_up/kkorthauer/FDR/benchmark-fdr/datasets/R/")

# read in test case example SB obj
load("/n/irizarryfs01_backed_up/kkorthauer/FDR/RESULTS/GWAS/bmi_summarizedBenchmark_1000.RData")

# rename default assay (bench) to qvalue
assayNames(sb) <- "qvalue"
sb <- addDefaultMetrics(sb)

# the following doesn't work, since I think it needs to connect the q-value 
# assay to a column of rowData?
rejections_scatter(sb)
names(rowData(sb))

# rename the 'bench' column of rowData; now the plotting function works
names(rowData(sb))[1] <- "qvalue"
rejections_scatter(sb)
```

**Comment by areyesq89** [comment]
It was a bug! When passing extra columns to `rowData`, the ground truth columns were not being flagged as ground truths and thus `assayNames` was not linking these columns to an assay.  If you run the `buildBench` step with the newest version it should work.

**Comment by kdkorthauer** [comment]
Thanks for tracking it down! I ran on the test subset and all is well again. 😄
